# Generated by Django 5.1.6 on 2025-03-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
